### ISSUE TITLE
Module not found error after upgrading plugin from 3.0.2 to 4.0.1

### ISSUE THREAD

**Issue by CodyKurtz** [abichinger/semantic-release-pypi#40]
After bumping the plugin version from 3.0.2 to 4.0.1, when I run semantic release, the following error is produced. I also tried setting the new envDir parameter to false, since I am creating my own virtual env. 

Here is my releaserc file

`{
  "plugins": [
  [
      "semantic-release-pypi",
      {
          "envDir": false
      }
  ],
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab"
],
  "branches": [
    "pypi-package"
  ]
}`

`[8:47:46 PM] [semantic-release] › ℹ  Running semantic-release version 24.1.2
[8:47:46 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/local/lib/node_modules/semantic-release-pypi/dist/prepare' imported from /usr/local/lib/node_modules/semantic-release-pypi/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///usr/local/lib/node_modules/semantic-release-pypi/dist/prepare'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/local/lib/node_modules/semantic-release-pypi/dist/prepare' imported from /usr/local/lib/node_modules/semantic-release-pypi/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///usr/local/lib/node_modules/semantic-release-pypi/dist/prepare'
}`

**Comment by abichinger** [comment]
Hi, thank you for bringing this to my attention.
Should be fixed by c37e49f6ccf608a638fb5bd883bac161b2bde753
